export type LayoutType =
  | 'single-classic'
  | 'single-centered'
  | 'sidebar-left-narrow'
  | 'sidebar-left-wide'
  | 'sidebar-right'
  | 'top-banner-photo'
  | 'two-column-balance'
  | 'header-card'

export type AccentStyle =
  | 'underline-bar'
  | 'left-bar'
  | 'side-icon'
  | 'background-pill'
  | 'thin-line'
  | 'double-line'
  | 'plain-bold'

export type FontPair =
  | 'modern-sans'
  | 'serif-heading'
  | 'mono-accent'

export interface TemplateConfig {
  id: string
  name: string
  categories: string[]
  free: boolean
  layout: LayoutType
  accentStyle: AccentStyle
  accentColor: string
  fontPair: FontPair
  showPhoto: boolean
  tag: string
  desc: string
}

export const TEMPLATES: TemplateConfig[] = [

  // ========== 5 FREE TEMPLATES ==========
  {
    id: 'classic-pro',
    name: '经典专业',
    categories: ['general', 'finance'],
    free: true,
    layout: 'single-classic',
    accentStyle: 'underline-bar',
    accentColor: '#1e293b',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '简洁·通用·ATS',
    desc: '单栏下划线标题，ATS 友好，适合所有行业',
  },
  {
    id: 'navy-modern',
    name: '深蓝现代',
    categories: ['tech', 'finance'],
    free: true,
    layout: 'sidebar-left-wide',
    accentStyle: 'plain-bold',
    accentColor: '#1e3a8a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '科技·金融·照片',
    desc: '左侧深色宽栏配头像，信息层次鲜明',
  },
  {
    id: 'minimal-line',
    name: '极简线条',
    categories: ['general', 'design'],
    free: true,
    layout: 'single-centered',
    accentStyle: 'thin-line',
    accentColor: '#0f172a',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '极简·衬线·居中',
    desc: '居中衬线标题，细线分隔，优雅克制',
  },
  {
    id: 'teal-creative',
    name: '青绿创意',
    categories: ['tech', 'design', 'general'],
    free: true,
    layout: 'sidebar-left-narrow',
    accentStyle: 'underline-bar',
    accentColor: '#0d9488',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '清新·侧栏·照片',
    desc: '左窄栏配头像，青绿点缀，现代清新',
  },
  {
    id: 'banner-warm',
    name: '横幅照片',
    categories: ['general'],
    free: true,
    layout: 'top-banner-photo',
    accentStyle: 'background-pill',
    accentColor: '#b45309',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '通用·横幅·照片',
    desc: '顶部彩色横幅带头像，胶囊式节标题',
  },

  // ========== 25 PRO TEMPLATES ==========
  // Each has a unique layout × accentStyle × fontPair combination

  // ── single-classic variants (4) ──
  {
    id: 'pro-classic-serif',
    name: '经典衬线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'left-bar',
    accentColor: '#1e3a8a',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '金融·法律·照片',
    desc: '衬线标题配左侧竖条，正式传统感强',
  },
  {
    id: 'pro-classic-double',
    name: '双线分隔',
    categories: ['general', 'finance'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'double-line',
    accentColor: '#374151',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '商务·严谨',
    desc: '双线节分隔，布局工整，适合传统行业',
  },
  {
    id: 'pro-classic-pill',
    name: '胶囊标题',
    categories: ['tech', 'general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'background-pill',
    accentColor: '#0d9488',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '科技·现代',
    desc: '节标题用底色胶囊，视觉跳跃感强',
  },
  {
    id: 'pro-classic-mono',
    name: '代码风格',
    categories: ['tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'side-icon',
    accentColor: '#16a34a',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '开发·工程师',
    desc: '等宽字体配图标标题，开发者专属气质',
  },

  // ── sidebar-left-narrow variants (4) ──
  {
    id: 'pro-narrow-serif',
    name: '窄栏衬线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'left-bar',
    accentColor: '#92400e',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '金融·咨询',
    desc: '左窄栏衬线字体，竖条标题，正式内敛',
  },
  {
    id: 'pro-narrow-pill',
    name: '窄栏胶囊',
    categories: ['tech', 'design'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'background-pill',
    accentColor: '#3b82f6',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '科技·产品',
    desc: '左窄栏搭配胶囊节标题，活泼现代',
  },
  {
    id: 'pro-narrow-mono',
    name: '窄栏等宽',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'plain-bold',
    accentColor: '#0c4a6e',
    fontPair: 'mono-accent',
    showPhoto: true,
    tag: '后端·架构',
    desc: '左窄栏等宽字体纯粗体，技术感十足',
  },
  {
    id: 'pro-narrow-double',
    name: '窄栏双线',
    categories: ['general', 'design'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'double-line',
    accentColor: '#6d28d9',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '创意·通用',
    desc: '左窄栏配双线节标题，独特视觉节奏',
  },

  // ── sidebar-left-wide variants (3) ──
  {
    id: 'pro-wide-serif',
    name: '宽栏衬线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'left-bar',
    accentColor: '#7f1d1d',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '高管·金融',
    desc: '深色宽栏配衬线字体，彰显资历与地位',
  },
  {
    id: 'pro-wide-icon',
    name: '宽栏图标',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'side-icon',
    accentColor: '#1e3a8a',
    fontPair: 'mono-accent',
    showPhoto: true,
    tag: '全栈·算法',
    desc: '宽栏侧边配图标等宽标题，工程师专属',
  },
  {
    id: 'pro-wide-double',
    name: '宽栏双线',
    categories: ['tech', 'general'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'double-line',
    accentColor: '#312e81',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '技术·管理',
    desc: '深色宽栏配双线节标题，结构感突出',
  },

  // ── sidebar-right variants (3) ──
  {
    id: 'pro-right-bar',
    name: '右栏竖条',
    categories: ['general', 'tech'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'left-bar',
    accentColor: '#0f766e',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '通用·清爽',
    desc: '主内容居左，右侧辅助栏，左竖条标题',
  },
  {
    id: 'pro-right-serif',
    name: '右栏典雅',
    categories: ['design', 'general'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'background-pill',
    accentColor: '#7c3aed',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '设计·艺术',
    desc: '右侧辅助栏配衬线胶囊标题，优雅创意',
  },
  {
    id: 'pro-right-thin',
    name: '右栏细线',
    categories: ['general', 'finance'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'thin-line',
    accentColor: '#0f172a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '简约·专业',
    desc: '右侧栏极细线分隔，克制而专业',
  },

  // ── top-banner-photo variants (2) ──
  {
    id: 'pro-banner-serif',
    name: '横幅衬线',
    categories: ['general', 'design'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'thin-line',
    accentColor: '#292524',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '人文·媒体',
    desc: '顶部横幅配衬线细线，黑白精致感',
  },
  {
    id: 'pro-banner-bar',
    name: '横幅竖条',
    categories: ['general'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'left-bar',
    accentColor: '#1d4ed8',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '通用·活力',
    desc: '顶部彩色横幅配左竖条节标题，层次清晰',
  },

  // ── two-column-balance variants (3) ──
  {
    id: 'pro-two-col-sans',
    name: '双栏商务',
    categories: ['general', 'finance'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'underline-bar',
    accentColor: '#1e3a8a',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '商务·信息密集',
    desc: '左右双栏平衡排列，信息密度高',
  },
  {
    id: 'pro-two-col-serif',
    name: '双栏衬线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'left-bar',
    accentColor: '#374151',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '咨询·金融',
    desc: '双栏平衡配衬线左竖条，精英气质',
  },
  {
    id: 'pro-two-col-pill',
    name: '双栏胶囊',
    categories: ['tech', 'design'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'background-pill',
    accentColor: '#ea580c',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '产品·运营',
    desc: '双栏平衡搭配胶囊标题，现代活力',
  },

  // ── header-card variants (4) ──
  {
    id: 'pro-card-minimal',
    name: '卡片极简',
    categories: ['general', 'design'],
    free: false,
    layout: 'header-card',
    accentStyle: 'thin-line',
    accentColor: '#0f172a',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '极简·留白',
    desc: '独立头部卡片配极细线，简洁留白',
  },
  {
    id: 'pro-card-serif',
    name: '卡片典雅',
    categories: ['finance', 'general'],
    free: false,
    layout: 'header-card',
    accentStyle: 'underline-bar',
    accentColor: '#1e3a8a',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '高管·律师',
    desc: '头部卡片配衬线下划线，沉稳典雅',
  },
  {
    id: 'pro-card-pill',
    name: '卡片活力',
    categories: ['general', 'tech'],
    free: false,
    layout: 'header-card',
    accentStyle: 'background-pill',
    accentColor: '#ec4899',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '市场·创意',
    desc: '头部卡片配彩色胶囊标题，个性鲜明',
  },
  {
    id: 'pro-card-mono',
    name: '卡片代码',
    categories: ['tech'],
    free: false,
    layout: 'header-card',
    accentStyle: 'side-icon',
    accentColor: '#16a34a',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '全栈·DevOps',
    desc: '头部卡片配等宽图标标题，开发者专属',
  },

  // ── single-centered variants (2) ──
  {
    id: 'pro-centered-serif',
    name: '居中典雅',
    categories: ['design', 'general'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'double-line',
    accentColor: '#1f2937',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '设计·学术',
    desc: '居中衬线配双线节标题，庄重典雅',
  },
  {
    id: 'pro-centered-pill',
    name: '居中胶囊',
    categories: ['general', 'tech'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'background-pill',
    accentColor: '#0d9488',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '通用·现代',
    desc: '居中排列配胶囊节标题，简洁现代',
  },

  // ========== 30 MORE PRO TEMPLATES (reaching 60 total) ==========

  // ── single-classic (5 more) ──
  {
    id: 'pro-classic-thin',
    name: '单栏细线',
    categories: ['general', 'design'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'thin-line',
    accentColor: '#334155',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '极简·ATS',
    desc: '单栏极细分割线，留白舒适，高度 ATS 友好',
  },
  {
    id: 'pro-classic-serif-photo',
    name: '经典照片栏',
    categories: ['finance', 'general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'underline-bar',
    accentColor: '#1a1a2e',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '金融·法律·照片',
    desc: '单栏衬线标题配头像，下划线节分隔，传统正式',
  },
  {
    id: 'pro-classic-bold-photo',
    name: '重磅单栏',
    categories: ['general', 'tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'plain-bold',
    accentColor: '#0f172a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '简洁·有力',
    desc: '粗体标题无装饰，头像加持，干练直接',
  },
  {
    id: 'pro-classic-icon-serif',
    name: '图标衬线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'side-icon',
    accentColor: '#7f1d1d',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '管理·咨询',
    desc: '衬线字体配节边图标，传统而不老气',
  },
  {
    id: 'pro-classic-mono-bar',
    name: '工程竖条',
    categories: ['tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'left-bar',
    accentColor: '#14532d',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '后端·运维',
    desc: '等宽字体配绿色左竖条，CLI 风格工程师简历',
  },

  // ── single-centered (4 more) ──
  {
    id: 'pro-centered-photo',
    name: '居中照片版',
    categories: ['general', 'design'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'underline-bar',
    accentColor: '#0f172a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '设计·媒体·照片',
    desc: '居中无衬线配头像，下划线节标题，平衡感强',
  },
  {
    id: 'pro-centered-bar',
    name: '居中竖条',
    categories: ['general', 'finance'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'left-bar',
    accentColor: '#1e3a8a',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '商务·简洁',
    desc: '居中排列配左侧竖条节标题，不对称美学',
  },
  {
    id: 'pro-centered-thin-photo',
    name: '居中轻盈照片',
    categories: ['design', 'general'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'thin-line',
    accentColor: '#374151',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '艺术·创意',
    desc: '居中细线分隔配头像，轻盈通透',
  },
  {
    id: 'pro-centered-bold',
    name: '居中粗体',
    categories: ['tech', 'general'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'plain-bold',
    accentColor: '#0c4a6e',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '产品·运营',
    desc: '居中布局配纯粗体节标题，干净有力',
  },

  // ── sidebar-left-narrow (3 more) ──
  {
    id: 'pro-narrow-icon',
    name: '窄栏图标标题',
    categories: ['tech', 'design'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'side-icon',
    accentColor: '#0f766e',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '产品·设计',
    desc: '左窄栏搭配侧边图标节标题，现代感强',
  },
  {
    id: 'pro-narrow-serif-photo',
    name: '窄栏典雅照片',
    categories: ['general', 'finance'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'thin-line',
    accentColor: '#292524',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '人文·媒体',
    desc: '左窄栏衬线字体配头像细线，精致优雅',
  },
  {
    id: 'pro-narrow-tech',
    name: '窄栏代码风',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'underline-bar',
    accentColor: '#1e3a8a',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '前端·工程师',
    desc: '左窄栏等宽字体配下划线，开发者简约风',
  },

  // ── sidebar-left-wide (3 more) ──
  {
    id: 'pro-wide-sans',
    name: '宽栏简约',
    categories: ['general', 'tech'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'underline-bar',
    accentColor: '#0f172a',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '科技·通用',
    desc: '深色宽栏无照片下划线，聚焦内容密度',
  },
  {
    id: 'pro-wide-pill',
    name: '宽栏活力照片',
    categories: ['tech', 'design'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'background-pill',
    accentColor: '#0d9488',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '创业·产品',
    desc: '深色宽栏配胶囊节标题和头像，活力现代',
  },
  {
    id: 'pro-wide-serif-thin',
    name: '宽栏衬线细线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'thin-line',
    accentColor: '#1a1a2e',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '高管·学术',
    desc: '深色宽栏衬线字体配极细线分隔，沉稳内敛',
  },

  // ── sidebar-right (3 more) ──
  {
    id: 'pro-right-tech',
    name: '右栏科技',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'side-icon',
    accentColor: '#0f766e',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '算法·架构',
    desc: '右侧辅助栏配等宽图标节标题，技术感突出',
  },
  {
    id: 'pro-right-double',
    name: '右栏双线',
    categories: ['general', 'finance'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'double-line',
    accentColor: '#1e3a8a',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '商务·条理清晰',
    desc: '右侧辅助栏配双线节标题，信息结构严谨',
  },
  {
    id: 'pro-right-serif-photo',
    name: '右栏衬线照片',
    categories: ['design', 'general'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'underline-bar',
    accentColor: '#292524',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '设计·编辑',
    desc: '右侧辅助栏衬线下划线配头像，文艺气质',
  },

  // ── top-banner-photo (3 more) ──
  {
    id: 'pro-banner-double',
    name: '横幅双线',
    categories: ['general', 'tech'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'double-line',
    accentColor: '#1e3a8a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '商务·层次感',
    desc: '顶部彩色横幅配双线节标题，商务层次清晰',
  },
  {
    id: 'pro-banner-tech',
    name: '横幅工程师',
    categories: ['tech'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'side-icon',
    accentColor: '#0f766e',
    fontPair: 'mono-accent',
    showPhoto: true,
    tag: '全栈·DevOps',
    desc: '横幅配等宽图标节标题，工程师气质十足',
  },
  {
    id: 'pro-banner-serif-classic',
    name: '横幅经典衬线',
    categories: ['finance', 'general'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'underline-bar',
    accentColor: '#1a1a2e',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '金融·法律',
    desc: '深色横幅配衬线下划线，严肃专业',
  },

  // ── two-column-balance (4 more) ──
  {
    id: 'pro-two-col-thin',
    name: '双栏极简',
    categories: ['general', 'design'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'thin-line',
    accentColor: '#374151',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '极简·留白',
    desc: '双栏平衡配极细分隔线，信息密集而不拥挤',
  },
  {
    id: 'pro-two-col-elegant',
    name: '双栏典雅',
    categories: ['finance', 'general'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'double-line',
    accentColor: '#1f2937',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '咨询·银行',
    desc: '双栏衬线配双线节标题，精英气质满满',
  },
  {
    id: 'pro-two-col-tech',
    name: '双栏工程',
    categories: ['tech'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'side-icon',
    accentColor: '#0c4a6e',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '全栈·数据',
    desc: '双栏等宽字体配图标节标题，工程师高密度简历',
  },
  {
    id: 'pro-two-col-bold-photo',
    name: '双栏重磅照片',
    categories: ['general', 'tech'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'plain-bold',
    accentColor: '#0f172a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '管理·市场',
    desc: '双栏粗体节标题配头像，强势有力',
  },

  // ── header-card (5 more) ──
  {
    id: 'pro-card-bar',
    name: '卡片竖条',
    categories: ['general', 'tech'],
    free: false,
    layout: 'header-card',
    accentStyle: 'left-bar',
    accentColor: '#0f766e',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '清爽·结构感',
    desc: '头部卡片配左侧竖条节标题，清爽有条理',
  },
  {
    id: 'pro-card-double-serif',
    name: '卡片典雅双线',
    categories: ['finance', 'design'],
    free: false,
    layout: 'header-card',
    accentStyle: 'double-line',
    accentColor: '#1f2937',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '学术·法律',
    desc: '头部卡片衬线字体配双线节标题，严谨典雅',
  },
  {
    id: 'pro-card-bold-mono',
    name: '卡片等宽重磅',
    categories: ['tech'],
    free: false,
    layout: 'header-card',
    accentStyle: 'plain-bold',
    accentColor: '#14532d',
    fontPair: 'mono-accent',
    showPhoto: true,
    tag: '后端·SRE',
    desc: '头部卡片等宽粗体配头像，硬核工程师专属',
  },
  {
    id: 'pro-card-tech-thin',
    name: '卡片科技细线',
    categories: ['tech', 'general'],
    free: false,
    layout: 'header-card',
    accentStyle: 'thin-line',
    accentColor: '#1e3a8a',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '前端·产品',
    desc: '头部卡片等宽细线，科技感与极简的融合',
  },
  {
    id: 'pro-card-sans-classic',
    name: '卡片通用无照片',
    categories: ['general', 'finance'],
    free: false,
    layout: 'header-card',
    accentStyle: 'underline-bar',
    accentColor: '#334155',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '通用·百搭',
    desc: '头部卡片无衬线下划线，百搭通用，ATS 友好',
  },
]

export const FREE_TEMPLATES = TEMPLATES.filter(t => t.free)
export const PRO_TEMPLATES = TEMPLATES.filter(t => !t.free)

export const CATEGORIES = ['全部', '科技', '设计', '金融', '通用']
export const CATEGORY_MAP: Record<string, string> = {
  '全部': 'all', '科技': 'tech', '设计': 'design', '金融': 'finance', '通用': 'general',
}

export function getTemplate(id: string): TemplateConfig {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
}
