// ============================================================
// 50 Templates inspired by 超级简历 / 简历本 / SmartResume
// All templates use white paper as base
// ============================================================

export type LayoutType =
  | 'single-classic'        // 经典单栏
  | 'single-centered'       // 居中标题单栏
  | 'sidebar-left-narrow'   // 左窄栏
  | 'sidebar-left-wide'     // 左宽栏（深色）
  | 'sidebar-right'         // 右栏
  | 'top-banner-photo'      // 顶部带头像横幅
  | 'two-column-balance'    // 双栏平衡
  | 'header-card'           // 头部独立卡片

export type AccentStyle =
  | 'underline-bar'         // 标题下加色条
  | 'left-bar'              // 标题左加竖条
  | 'side-icon'             // 标题左加图标
  | 'background-pill'       // 标题底色块
  | 'thin-line'             // 极细线
  | 'double-line'           // 双线
  | 'plain-bold'            // 纯粗体无装饰

export type FontPair =
  | 'modern-sans'           // 全 Inter
  | 'serif-heading'         // 标题衬线 + 正文无衬线
  | 'mono-accent'           // 强调用等宽

export interface TemplateConfig {
  id: string
  name: string
  categories: string[]      // 'tech' | 'design' | 'finance' | 'general'
  free: boolean
  layout: LayoutType
  accentStyle: AccentStyle
  accentColor: string
  fontPair: FontPair
  showPhoto: boolean        // 是否显示头像区域
  tag: string
  desc: string
}

export const TEMPLATES: TemplateConfig[] = [

  // ========== 5 FREE TEMPLATES ==========
  {
    id: 'classic-pro',
    name: '经典专业',
    categories: ['general', 'finance'],
    free: true,
    layout: 'single-classic',
    accentStyle: 'underline-bar',
    accentColor: '#1e293b',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '简洁·通用',
    desc: '简洁大方，适合任何行业',
  },
  {
    id: 'navy-modern',
    name: '深蓝现代',
    categories: ['tech', 'finance'],
    free: true,
    layout: 'sidebar-left-wide',
    accentStyle: 'plain-bold',
    accentColor: '#1e3a8a',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '科技·金融',
    desc: '左侧深色栏配头像，专业稳重',
  },
  {
    id: 'minimal-line',
    name: '极简线条',
    categories: ['general', 'design'],
    free: true,
    layout: 'single-centered',
    accentStyle: 'thin-line',
    accentColor: '#0f172a',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '极简·设计',
    desc: '居中标题，细线分隔，优雅',
  },
  {
    id: 'teal-creative',
    name: '青绿创意',
    categories: ['tech', 'design', 'general'],
    free: true,
    layout: 'sidebar-left-narrow',
    accentStyle: 'underline-bar',
    accentColor: '#0d9488',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '清新·创意',
    desc: '青绿点缀，现代清新',
  },
  {
    id: 'banner-warm',
    name: '暖色横幅',
    categories: ['general'],
    free: true,
    layout: 'top-banner-photo',
    accentStyle: 'background-pill',
    accentColor: '#b45309',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '通用·亲和',
    desc: '顶部横幅带头像，亲和力强',
  },

  // ========== 25 PRO TEMPLATES ==========

  // Tech/IT (8)
  {
    id: 'pro-engineer',
    name: '工程师专业',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'left-bar',
    accentColor: '#0f3460',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '工程·后端',
    desc: '深蓝左栏，工程师标配',
  },
  {
    id: 'pro-frontend',
    name: '前端工程师',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'underline-bar',
    accentColor: '#7c3aed',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '前端·全栈',
    desc: '紫色调，前端开发者首选',
  },
  {
    id: 'pro-product',
    name: '产品经理',
    categories: ['tech'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'underline-bar',
    accentColor: '#ea580c',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '产品·运营',
    desc: '双栏平衡，信息密度高',
  },
  {
    id: 'pro-data',
    name: '数据分析师',
    categories: ['tech', 'finance'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'left-bar',
    accentColor: '#0e7490',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '数据·分析',
    desc: '右侧栏布局，数据感强',
  },
  {
    id: 'pro-devops',
    name: 'DevOps 工程师',
    categories: ['tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'side-icon',
    accentColor: '#16a34a',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '运维·架构',
    desc: '等宽字体，技术氛围浓',
  },
  {
    id: 'pro-mobile',
    name: '移动端开发',
    categories: ['tech'],
    free: false,
    layout: 'header-card',
    accentStyle: 'background-pill',
    accentColor: '#3b82f6',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '移动·iOS·安卓',
    desc: '头部卡片样式',
  },
  {
    id: 'pro-ai',
    name: 'AI 算法工程师',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'plain-bold',
    accentColor: '#1e1b4b',
    fontPair: 'mono-accent',
    showPhoto: true,
    tag: '算法·ML',
    desc: '深紫调，算法工程师专属',
  },
  {
    id: 'pro-test',
    name: '测试工程师',
    categories: ['tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'double-line',
    accentColor: '#475569',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '测试·QA',
    desc: '严谨双线，QA 风格',
  },

  // Design (5)
  {
    id: 'pro-uiux',
    name: 'UI/UX 设计师',
    categories: ['design'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'background-pill',
    accentColor: '#ec4899',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '交互·视觉',
    desc: '玫粉色调，设计师专属',
  },
  {
    id: 'pro-graphic',
    name: '平面设计师',
    categories: ['design'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'thin-line',
    accentColor: '#0f172a',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '平面·品牌',
    desc: '黑白经典，平面设计感',
  },
  {
    id: 'pro-brand',
    name: '品牌设计',
    categories: ['design'],
    free: false,
    layout: 'header-card',
    accentStyle: 'left-bar',
    accentColor: '#dc2626',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '品牌·营销',
    desc: '红色热情，品牌创意',
  },
  {
    id: 'pro-illust',
    name: '插画师',
    categories: ['design'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'underline-bar',
    accentColor: '#ca8a04',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '插画·漫画',
    desc: '暖黄色调，艺术感浓',
  },
  {
    id: 'pro-motion',
    name: '动效设计',
    categories: ['design'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'background-pill',
    accentColor: '#06b6d4',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '动效·3D',
    desc: '青蓝活泼，动效专属',
  },

  // Finance/Business (5)
  {
    id: 'pro-banker',
    name: '银行金融',
    categories: ['finance'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'underline-bar',
    accentColor: '#1e3a8a',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '银行·投行',
    desc: '深蓝衬线，金融精英',
  },
  {
    id: 'pro-consult',
    name: '咨询顾问',
    categories: ['finance'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'left-bar',
    accentColor: '#374151',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '咨询·战略',
    desc: '商务灰，咨询顾问首选',
  },
  {
    id: 'pro-accounting',
    name: '会计审计',
    categories: ['finance'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'thin-line',
    accentColor: '#854d0e',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '会计·审计',
    desc: '暖金衬线，正式严谨',
  },
  {
    id: 'pro-legal',
    name: '律师法务',
    categories: ['finance'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'double-line',
    accentColor: '#1f2937',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '律师·法务',
    desc: '居中庄重，法律专业',
  },
  {
    id: 'pro-investment',
    name: '投资分析',
    categories: ['finance'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'plain-bold',
    accentColor: '#7f1d1d',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '投资·并购',
    desc: '深红衬线，投资精英',
  },

  // General/Cross-industry (7)
  {
    id: 'pro-fresh-grad',
    name: '应届毕业生',
    categories: ['general'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'background-pill',
    accentColor: '#0d9488',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '应届·实习',
    desc: '清新活泼，校招首选',
  },
  {
    id: 'pro-executive',
    name: '高管行政',
    categories: ['general', 'finance'],
    free: false,
    layout: 'header-card',
    accentStyle: 'underline-bar',
    accentColor: '#0f172a',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '高管·总监',
    desc: '沉稳大气，彰显资历',
  },
  {
    id: 'pro-sales',
    name: '销售业务',
    categories: ['general'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'background-pill',
    accentColor: '#dc2626',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '销售·BD',
    desc: '红色冲击力，销售首选',
  },
  {
    id: 'pro-hr',
    name: 'HR 人力资源',
    categories: ['general'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'left-bar',
    accentColor: '#9333ea',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: 'HR·招聘',
    desc: '紫色温和，人力专业',
  },
  {
    id: 'pro-medical',
    name: '医疗医生',
    categories: ['general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'underline-bar',
    accentColor: '#0891b2',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '医疗·护理',
    desc: '医疗蓝，专业可信',
  },
  {
    id: 'pro-teacher',
    name: '教师教育',
    categories: ['general'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'left-bar',
    accentColor: '#4f46e5',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '教师·培训',
    desc: '靛蓝衬线，教育行业',
  },
  {
    id: 'pro-marketing',
    name: '市场营销',
    categories: ['general'],
    free: false,
    layout: 'header-card',
    accentStyle: 'background-pill',
    accentColor: '#f59e0b',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '市场·营销',
    desc: '金黄活力，营销出彩',
  },

  // ========== 20 MORE PRO TEMPLATES (total 50) ==========

  // Academia / Research (2)
  {
    id: 'pro-academia',
    name: '学术研究员',
    categories: ['general', 'tech'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'left-bar',
    accentColor: '#1e3a8a',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '学术·科研',
    desc: '右侧栏衬线字体，学术范十足',
  },
  {
    id: 'pro-professor',
    name: '高校教授',
    categories: ['general'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'double-line',
    accentColor: '#1f2937',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '教授·学者',
    desc: '居中双线，权威学者风格',
  },

  // Engineering / Technical (3)
  {
    id: 'pro-embedded',
    name: '嵌入式/硬件',
    categories: ['tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'side-icon',
    accentColor: '#0c4a6e',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '嵌入式·硬件',
    desc: '等宽字体，硬件工程师气质',
  },
  {
    id: 'pro-security',
    name: '网络安全',
    categories: ['tech'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'left-bar',
    accentColor: '#14532d',
    fontPair: 'mono-accent',
    showPhoto: false,
    tag: '安全·渗透',
    desc: '深绿等宽，安全工程师首选',
  },
  {
    id: 'pro-cto',
    name: '技术总监/CTO',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'double-line',
    accentColor: '#1e1b4b',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '架构师·CTO',
    desc: '深紫双线，展现技术领导力',
  },

  // Design / Creative (3)
  {
    id: 'pro-3d-artist',
    name: '3D/视觉艺术',
    categories: ['design'],
    free: false,
    layout: 'header-card',
    accentStyle: 'background-pill',
    accentColor: '#701a75',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '3D·视觉',
    desc: '深紫胶囊标题，视觉冲击力强',
  },
  {
    id: 'pro-copywriter',
    name: '文案/策划',
    categories: ['design', 'general'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'underline-bar',
    accentColor: '#292524',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '文案·创意',
    desc: '居中衬线，文字工作者专属',
  },
  {
    id: 'pro-photographer',
    name: '摄影师',
    categories: ['design'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'plain-bold',
    accentColor: '#0f172a',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '摄影·视频',
    desc: '黑白极简，凸显作品质感',
  },

  // Finance / Business (3)
  {
    id: 'pro-venture',
    name: '投融资/风投',
    categories: ['finance'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'underline-bar',
    accentColor: '#7c2d12',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '风投·私募',
    desc: '砖红衬线，VC 精英风格',
  },
  {
    id: 'pro-cfo',
    name: '财务总监 CFO',
    categories: ['finance'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'underline-bar',
    accentColor: '#0f4c81',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: 'CFO·财务',
    desc: '经典深蓝，财务高管必备',
  },
  {
    id: 'pro-startup',
    name: '创业者/联合创始人',
    categories: ['general', 'finance'],
    free: false,
    layout: 'header-card',
    accentStyle: 'side-icon',
    accentColor: '#0f766e',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '创业·融资',
    desc: '青绿图标，创业精神气质',
  },

  // General / Service (6)
  {
    id: 'pro-pm-ops',
    name: '运营/项目经理',
    categories: ['general', 'tech'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'left-bar',
    accentColor: '#0369a1',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '运营·项目',
    desc: '蓝色双栏，信息密度高',
  },
  {
    id: 'pro-supply-chain',
    name: '供应链管理',
    categories: ['general', 'finance'],
    free: false,
    layout: 'sidebar-left-narrow',
    accentStyle: 'thin-line',
    accentColor: '#1e40af',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '供应链·采购',
    desc: '细线分隔，逻辑清晰',
  },
  {
    id: 'pro-hospitality',
    name: '酒店/餐饮服务',
    categories: ['general'],
    free: false,
    layout: 'top-banner-photo',
    accentStyle: 'background-pill',
    accentColor: '#b45309',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '酒店·服务',
    desc: '暖棕横幅，服务行业亲和力',
  },
  {
    id: 'pro-social-work',
    name: '公益/社工',
    categories: ['general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'background-pill',
    accentColor: '#065f46',
    fontPair: 'modern-sans',
    showPhoto: false,
    tag: '公益·NGO',
    desc: '深绿胶囊，公益人文关怀',
  },
  {
    id: 'pro-journalist',
    name: '记者/媒体人',
    categories: ['general'],
    free: false,
    layout: 'single-centered',
    accentStyle: 'thin-line',
    accentColor: '#292524',
    fontPair: 'serif-heading',
    showPhoto: false,
    tag: '记者·编辑',
    desc: '黑白极简，媒体从业者首选',
  },
  {
    id: 'pro-nurse',
    name: '护士/医技人员',
    categories: ['general'],
    free: false,
    layout: 'single-classic',
    accentStyle: 'left-bar',
    accentColor: '#0891b2',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '护理·医技',
    desc: '天蓝竖条，医疗专业可信',
  },
  {
    id: 'pro-trainer',
    name: '企业培训师',
    categories: ['general'],
    free: false,
    layout: 'two-column-balance',
    accentStyle: 'underline-bar',
    accentColor: '#4338ca',
    fontPair: 'modern-sans',
    showPhoto: true,
    tag: '培训·讲师',
    desc: '靛紫双栏，讲师气场十足',
  },
  {
    id: 'pro-game-dev',
    name: '游戏开发',
    categories: ['tech'],
    free: false,
    layout: 'sidebar-left-wide',
    accentStyle: 'side-icon',
    accentColor: '#6d28d9',
    fontPair: 'mono-accent',
    showPhoto: true,
    tag: '游戏·引擎',
    desc: '紫色图标，游戏开发者专属',
  },
  {
    id: 'pro-interior',
    name: '室内设计师',
    categories: ['design'],
    free: false,
    layout: 'sidebar-right',
    accentStyle: 'background-pill',
    accentColor: '#9a3412',
    fontPair: 'serif-heading',
    showPhoto: true,
    tag: '室内·空间',
    desc: '砖红胶囊，空间美学气质',
  },
]

// Helpers
export const FREE_TEMPLATES = TEMPLATES.filter(t => t.free)
export const PRO_TEMPLATES = TEMPLATES.filter(t => !t.free)

export const CATEGORIES = ['全部', '科技', '设计', '金融', '通用']
export const CATEGORY_MAP: Record<string, string> = {
  '全部': 'all', '科技': 'tech', '设计': 'design', '金融': 'finance', '通用': 'general',
}

export function getTemplate(id: string): TemplateConfig {
  return TEMPLATES.find(t => t.id === id) || TEMPLATES[0]
}
